server:
  port: 8080 

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8099/eureka/
      defaultZone: http://registry-service:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-pedidos-route
          uri: lb://ms-pedidos
          predicates:
            - Path=/api/pedidos/**
          filters: 
            - PreserveHostHeader 
        - id: ms-productos-route
          uri: lb://product-ms-v2
          predicates:
            - Path=/api/productos/**
          filters: 
            - PreserveHostHeader

        - id: ms-authorization-server-oauth
          uri: lb://MS-AUTHORIZATION-SERVER
          predicates:
            - Path=/oauth2/**
          filters: 
            - PreserveHostHeader 

        - id: ms-authorization-server-well-known
          uri: lb://MS-AUTHORIZATION-SERVER
          predicates:
            - Path=/.well-known/**
          filters: 
            - PreserveHostHeader 

        - id: ms-authorization-server-login
          uri: lb://MS-AUTHORIZATION-SERVER
          predicates:
            - Path=/login
          filters: 
            - PreserveHostHeader 

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ms-authorization-server:9000