server:
  port: 8082
spring:
  # --- Configuración Reactiva (R2DBC) ---
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_dev
    username: postgres
    password: 3264 # Tu contraseña
    pool:
      enabled: true
  # R2DBC no tiene ddl-auto, pero se puede inicializar la BD con un script
  sql:
    init:
      mode: always 

# --- URL para comunicarse con ms-productos ---
ms-productos:
  url: http://localhost:8081
eureka:
  client:
    serviceUrl:
      
      defaultZone: http://localhost:8099/eureka/

resilience4j:
  circuitbreaker:
    instances:
      
      
      productos-cb: 
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED   #  N° de llamadas
        slidingWindowSize: 10            # Revisa las últimas 10 llamadas
        failureRateThreshold: 50         # Si 5 de esas 10 fallan (50%), se "abre"
        waitDurationInOpenState: 10s     # "abierto" por 10 segundos
        permittedNumberOfCallsInHalfOpenState: 3 # En 10s, deja pasar 3 llamadas de prueba