server:
  port: 8082
spring:
  # --- Configuración Reactiva (R2DBC) ---
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_dev
    username: postgres
    password: 3264 # Tu contraseña
    pool:
      enabled: true
  # R2DBC no tiene ddl-auto, pero podemos inicializar la BD con un script
  sql:
    init:
      mode: always 

# --- URL para comunicarse con ms-productos ---
ms-productos:
  url: http://localhost:8081
eureka:
  client:
    serviceUrl:
      # Esta es la dirección de tu "agenda" (el registry-service en el puerto 8099)
      defaultZone: http://localhost:8099/eureka/