# JPA no tiene puerto (api web)
spring:
  datasource:
    # Apunta al contenedor de la base de datos
    url: jdbc:postgresql://postgres-db:5432/sistema_pedidos_db
    username: postgres
    password: postgres 
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # No hiberna intente crear/borrar tablas
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/