server:
  port: 8081
spring:
  # --- Configuración Reactiva (R2DBC) ---
  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/sistema_pedidos_db
    username: postgres
    password: postgres 
    pool:
      enabled: true
  
  
  security:
    oauth2:
      resourceserver:
        jwt:
          # Valida el token contra el Gateway (o el Auth Server directamente)
          issuer-uri: http://gateway-service:8080 

logging:
  level:
    root: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/