# JPA no tiene puerto (api web)
spring:
  datasource:
    # Apunta al contenedor de la base de datos
    url: jdbc:postgresql://postgres-db:5432/sistema_pedidos_db
    username: postgres
    password: postgres 
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    
    bootstrap-servers: kafka-broker:9092
    
    
    consumer:
      
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/